In [1]:
import numpy as np

data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [2]:

data2 = [0, 1.5, 2, 3.7, 4, 5.2]		# 실수와 정수가 혼합되어 있는 리스트
a2 = np.array(data2)			
a2

array([0. , 1.5, 2. , 3.7, 4. , 5.2])

In [4]:
a3 = np.array([0.5, 2, 0.01, 8])
a3

array([0.5 , 2.  , 0.01, 8.  ])

In [6]:
a4 = np.array([[1,2,3], [4,5,6]])		# 2차원(2X3) 배열 생성
a4

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
ar1 = np.arange(0,10,2)		# 0부터 9까지 2씩 더한 수들로 배열 생성
ar2 = np.arange(1,10)		# step 생략하고 1부터 9까지 1씩 더한 수들로 배열 생성
ar3 = np.arange(5)			# star, step 생략하고 0부터 4까지 1씩 더한 수들로 배열 생성

print(ar1)
print(ar2)
print(ar3)

[0 2 4 6 8]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [12]:
ar4 = np.arange(12).reshape(4,3)	# 0부터 11까지 12개의 원소를 4x3행렬(배열)로 생성
ar5 = np.arange(1,10).reshape(3,3)	# 1부터 9까지 9개의 원소를 3x3 배열로 생성
ar6 = np.arange(1,24,2).reshape(2,6) # 1부터 23까지 2씩 건너뛰며 만든 12개의 원소로 2x6 배열
ar7 = np.arange(10)			# 0부터 9까지 10개의 원소를 1차원 배열로 생성

print(ar4)
print(ar4.shape, '\n')		# 배열의 형태 확인
print(ar5)
print(ar5.shape, '\n')
print(ar6)
print(ar6.shape, '\n')
print(ar7)
print(ar7.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3) 

[[ 1  3  5  7  9 11]
 [13 15 17 19 21 23]]
(2, 6) 

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [13]:
lar1 = np.linspace(1, 10, 10)	# 1부터 10까지 10개의 데이터로 배열 생성
lar2 = np.linspace(0, np.pi, 20)  # 0부터 pi(3.141592..)까지 동일한 간격으로 나눈 20개의 
								  # 데이터로 배열 새성
print(lar1)
print(lar2)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0.         0.16534698 0.33069396 0.49604095 0.66138793 0.82673491
 0.99208189 1.15742887 1.32277585 1.48812284 1.65346982 1.8188168
 1.98416378 2.14951076 2.31485774 2.48020473 2.64555171 2.81089869
 2.97624567 3.14159265]


In [15]:
lar3 = np.linspace(1,12,12).reshape(3,4)
print(lar3)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [16]:
arz1 = np.zeros(5)
arz2 = np.zeros((5,3))

print(arz1)
print(arz2)


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
aro1 = np.ones(4)
aro2 = np.ones((4,6))

print(aro1)
print(aro2)

[1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [18]:
are1 = np.eye(3)
are2 = np.eye(5)
are3 = np.eye(2)

print(are1)
print(are2)
print(are3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0.]
 [0. 1.]]


In [19]:
are1.dtype

dtype('float64')

In [20]:
strarr = np.array(['1', '2', '3'])
strarr.dtype


dtype('<U1')

In [21]:
art1 = np.array([True, False])
art1.dtype

dtype('bool')

In [24]:
str_ar1 = np.array(['1.234', '0.123', '5.123', '9', '3'])
num_ar1 = str_ar1.astype(float)		# 문자열인 원소를 실수로 변환
print(num_ar1)

print(str_ar1.dtype)
print(num_ar1.dtype)

[1.234 0.123 5.123 9.    3.   ]
<U5
float64


In [25]:
str_ar2 = np.array(['1', '2', '3', '4'])
num_ar2 = str_ar2.astype(int)		# 문자열인 원소를 실수로 변환
print(num_ar2)

print(str_ar2.dtype)
print(num_ar2.dtype)

[1 2 3 4]
<U1
int64


In [26]:
num_f1 = np.array([10, 21, 3.13, 2.72, 5.84])
num_i1 = num_f1.astype(int)
print(num_i1)

print(num_f1.dtype)
print(num_i1.dtype)

[10 21  3  2  5]
float64
int64


In [29]:
print(np.random.rand(2,3,4,5))

[[[[0.00202127 0.3695416  0.21135216 0.83784807 0.57447243]
   [0.48221474 0.04900133 0.82121964 0.71190741 0.88717572]
   [0.09913069 0.26135703 0.94231989 0.50974675 0.7986958 ]
   [0.05291944 0.39616211 0.60854899 0.41322672 0.27154362]]

  [[0.89881726 0.19157919 0.87118199 0.29808622 0.15613474]
   [0.83499242 0.82380805 0.84486306 0.07937489 0.05476176]
   [0.53974372 0.29915487 0.26001815 0.21919389 0.64379514]
   [0.45680999 0.45675408 0.65548658 0.20985425 0.09246667]]

  [[0.21755571 0.76683266 0.64442828 0.76924488 0.98646802]
   [0.84604077 0.85968881 0.28893983 0.41832008 0.78969123]
   [0.78560848 0.52276937 0.0227374  0.18009562 0.29675067]
   [0.06978465 0.22430706 0.11078852 0.61505909 0.06508429]]]


 [[[0.35031186 0.75080188 0.47801655 0.58781204 0.95069925]
   [0.03313698 0.70448955 0.78363116 0.07622222 0.94926824]
   [0.27247896 0.55716086 0.68350819 0.25720577 0.05630153]
   [0.583333   0.15969582 0.00225311 0.97993268 0.90321815]]

  [[0.73204082 0.72597676 0.90

In [31]:
ran_arr1 = np.random.rand()
ran_arr2 = np.random.rand(3)
ran_arr3 = np.random.rand(2,3)
ran_arr4 = np.random.rand(2,3,4)

print(ran_arr1)
print()
print(ran_arr2)
print()
print(ran_arr3)
print()
print(ran_arr4)

0.44824395969215336

[0.15747727 0.6874496  0.29830424]

[[0.81029893 0.66345291 0.37985234]
 [0.47439082 0.71376514 0.25358668]]

[[[0.25357439 0.26794274 0.04588856 0.99637639]
  [0.87959056 0.45172073 0.01973225 0.02945277]
  [0.4701212  0.00228858 0.40887994 0.76236931]]

 [[0.2796868  0.01650915 0.19587565 0.47992455]
  [0.38996545 0.64219117 0.34302551 0.55801736]
  [0.842475   0.43343198 0.1603189  0.62443745]]]


In [32]:
rani_arr1 = np.random.randint(6)	# 0부터 5까지의 난수 1개 
rani_arr2 = np.random.randint(1,10) # 1부터 9까지의 난수 1개
rani_arr3 = np.random.randint(1,30, size=(5))	# 1~29 5개의 난수를 원소로 갖는 1차원 배열
rani_arr4 = np.random.randint(1,30, size=(3,4))	# 1~29 난수를 원소로 갖는 3x4배열 생성
rani_arr5 = np.random.randint(20, size=(2,3,4))	# 0~19 난수를 원소로 갖는 2x3x4배열 생성

print(rani_arr1)
print(rani_arr2)
print(rani_arr3)
print(rani_arr4)
print(rani_arr5)

0
9
[ 5  7 22 27 24]
[[13 28 12 18]
 [21 16 21  4]
 [21 26 23 10]]
[[[12 16 18 12]
  [10  4 12 13]
  [13  6 11 13]]

 [[ 0  3 11  4]
  [ 3  2  5 15]
  [ 9  4 16  7]]]


In [33]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,4,6,8,10])

print(arr1>arr2)

[False False False False False]


In [41]:
arr1 = np.array([[1,2,3], [4,5,6]])		# 2x3인 배열
arr2 = np.array([[2,4,3], [2,10,12]])		# 2x3인 배열

# 더하기 연산
arr_res1 = arr1 + arr2
print("===== 배열의 더하기 연산 =====")
print(arr_res1)

# 빼기 연산
arr_res2 = arr2 - arr1
print("===== 배열의 빼기 연산 =====")
print(arr_res2)

# 상수배 연산
arr_res3 = arr1 * 5
print("===== 배열의 상수배 연산 =====")
print(arr_res3)

# 곱하기 연산
arr_res4 = arr1 * arr2
print("===== 배열의 곱하기 연산 =====")
print(arr_res4)

# 거듭제곱 연산
arr_res5 = arr1 ** 2
print("===== 배열의 거듭제곱 연산 =====")
print(arr_res5)

# 나누기 연산
arr_res6 = arr2 / arr1
print("===== 배열의 나누기 연산 =====")
print(arr_res6)

# 비교 연산
arr_res7 = arr2 <= arr1
arr_res8 = arr2 > 3
print("===== 배열의 비교 연산 =====")
print(arr_res7)
print()
print(arr_res8)

===== 배열의 더하기 연산 =====
[[ 3  6  6]
 [ 6 15 18]]
===== 배열의 빼기 연산 =====
[[ 1  2  0]
 [-2  5  6]]
===== 배열의 상수배 연산 =====
[[ 5 10 15]
 [20 25 30]]
===== 배열의 곱하기 연산 =====
[[ 2  8  9]
 [ 8 50 72]]
===== 배열의 거듭제곱 연산 =====
[[ 1  4  9]
 [16 25 36]]
===== 배열의 나누기 연산 =====
[[2.  2.  1. ]
 [0.5 2.  2. ]]
===== 배열의 비교 연산 =====
[[False False  True]
 [ True False False]]

[[False  True False]
 [False  True  True]]


In [35]:
arr3 = np.arange(5)
print(arr3)

[0 1 2 3 4]


In [37]:
arr3 = np.arange(12).reshape(2,6)
arr3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [38]:
arr3.std()

3.452052529534663

In [39]:
arr3.max()

11

In [42]:
arr3 = np.random.randint(1,3, size =(2,3))	# 1부터 3까지의 정수 난수를 원소로하는 2x3배열
print("arr3 배열")
print(arr3)

# 합 구하기
res1 = arr3.sum()
print("===== 배열의 합 =====")
print(res1)

# 평균 구하기
res2 = arr3.mean()
print("===== 배열의 평균 =====")
print(res2)

# 표준편차 구하기
res3 = arr3.std()
print("===== 배열의 표준편차 =====")
print(res3)

# 분산 구하기
res4 = arr3.var()
print("===== 배열의 분산 =====")
print(res4)

# 최댓값 구하기
res5 = arr3.max()
print("===== 배열의 최댓값 =====")
print(res5)

# 최솟값 구하기
res6 = arr3.min()
print("===== 배열의 최솟값 =====")
print(res6)

# 누적합 구하기
arr_res7 = arr3.cumsum()
print("===== 배열의 누적합 =====")
print(arr_res7)

# 누적곱 구하기
arr_res8 = arr3.cumprod()
print("===== 배열의 누적곱 =====")
print(arr_res8)

arr3 배열
[[1 2 1]
 [2 1 1]]
===== 배열의 합 =====
8
===== 배열의 평균 =====
1.3333333333333333
===== 배열의 표준편차 =====
0.4714045207910317
===== 배열의 분산 =====
0.22222222222222224
===== 배열의 최댓값 =====
2
===== 배열의 최솟값 =====
1
===== 배열의 누적합 =====
[1 3 4 6 7 8]
===== 배열의 누적곱 =====
[1 2 2 4 4 4]


In [43]:
A = np.array([1,2,2,3]).reshape(2,2)
B = np.array([3,2,1,2]).reshape(2,2)

# 행렬곱 구하기
mat_res1 = A.dot(B)		# 또는 np.dot(A,B)
print("===== 행렬곱 =====")
print(mat_res1)

# 전치행렬 구하기
mat_res2 = np.transpose(A)
mat_res3 = B.transpose()
print("===== A의 전치행렬 =====")
print(mat_res2)
print("===== B의 전치행렬 =====")
print(mat_res3)

# 역행렬 구하기
mat_res4 = np.linalg.inv(A)
mat_res5 = np.linalg.inv(B)
print("===== A의 역행렬 =====")
print(mat_res4)
print("===== B의 역행렬 =====")
print(mat_res5)

# det(A)/ det(B) 구하기
res6 = np.linalg.det(A)
res7 = np.linalg.det(B)
print("===== det(A) 구하기 =====")
print(res6)
print("===== det(B) 구하기 =====")
print(res7)

===== 행렬곱 =====
[[ 5  6]
 [ 9 10]]
===== A의 전치행렬 =====
[[1 2]
 [2 3]]
===== B의 전치행렬 =====
[[3 1]
 [2 2]]
===== A의 역행렬 =====
[[-3.  2.]
 [ 2. -1.]]
===== B의 역행렬 =====
[[ 0.5  -0.5 ]
 [-0.25  0.75]]
===== det(A) 구하기 =====
-1.0
===== det(B) 구하기 =====
4.000000000000001


In [44]:
a1 = np.array([0, 10, 20, 30, 40, 50])		# 1차원 배열 생성

print('a1[0] = ', a1[0])
print('a1[4] = ', a1[4])		# 배열에서 인덱스가 4에 해당하는 원소 출력

a1[5] = 70					# 6번째 원소(50)의 값을 70으로 변경
print("modified a1")
print(a1)

print('a1[[1,3,4]] = ', a1[[1,3,4]])	# 인덱스가 1, 3, 4인 원소들을 모두 출력

a2 = np.arange(10,100,10).reshape(3,3)	# 2차원 배열 생성
print('a2')
print(a2)

print('a2[0,2] = ', a2[0,2])	# (0,2) 위치의 원소 출력

a2[2,2] = 95			# (2,2)위치의 원소 값을 95로 변경
print('modified a2')
print(a2)

print('a2[1] = ', a2[1])	# 두번째 행 전체 출력

a2[1] = np.array([45,55,65])	# 두번째 행 전체의 값을 변경
print('modified a2')
print(a2)

a2[2] = [47,57,67]		# 세번쨰 행 전체의 값을 변경
print('modified a2')
print(a2)

print('a2의 (0,0), (2,1) = ', a2[[0,2],[0,1]]) 	# (0,0), (2,1) 원소 동시에 출력

a = np.array([1,2,3,4,5,6])		# 새로운 1차원 배열 생성
print("3보다 큰 원소 : ", a[a>3])	# 조건을 만족하는 원소 출력

a1[0] =  0
a1[4] =  40
modified a1
[ 0 10 20 30 40 70]
a1[[1,3,4]] =  [10 30 40]
a2
[[10 20 30]
 [40 50 60]
 [70 80 90]]
a2[0,2] =  30
modified a2
[[10 20 30]
 [40 50 60]
 [70 80 95]]
a2[1] =  [40 50 60]
modified a2
[[10 20 30]
 [45 55 65]
 [70 80 95]]
modified a2
[[10 20 30]
 [45 55 65]
 [47 57 67]]
a2의 (0,0), (2,1) =  [10 57]
3보다 큰 원소 :  [4 5 6]


In [46]:
b1 = np.array([0,10,20,30,40,50])

print('b1[1:4] : ', b1[1:4])	# b1의 인덱스가 1~3까지의 원소 출력
print('b1[:3] : ', b1[:3])		# b1의 인덱스가 0~2까지의 원소 출력
print('b1[2:] : ', b1[2:])		# b1의 인덱스가 2~5까지의 원소 출력

b1[2:5] = np.array([25, 35, 45])	# 범위 지정해서 원소의 값 변경
print('modified b1')
print(b1)

b1[3:6] = 60		# 범위의 원소들을 하나의 값으로 변경(모두 60으로 변경)
print('modified b1')
print(b1)

b2 = np.arange(10,100,10).reshape(3,3)	
print('b2')
print(b2)

print('b2[1:3, 1:3] : ', b2[1:3, 1:3])	# 행, 열이 1~2 인덱스인 범위의 원소 출력
print('b2[:3, 1:] : ', b2[:3, 1:])	# 0~2의 행, 1~2까지의 열의 원소 출력

print('b2[1][0:2] : ',b2[1][0:2] ) # 1행에서 0~1열의 원소 출력

b2[0:2, 1:3] = np.array([[25,35],[55,65]])	# 범위 지정해서 원소 값 변경
print('modified b2')
print(b2)

b1[1:4] :  [10 20 30]
b1[:3] :  [ 0 10 20]
b1[2:] :  [20 30 40 50]
modified b1
[ 0 10 25 35 45 50]
modified b1
[ 0 10 25 60 60 60]
b2
[[10 20 30]
 [40 50 60]
 [70 80 90]]
b2[1:3, 1:3] :  [[50 60]
 [80 90]]
b2[:3, 1:] :  [[20 30]
 [50 60]
 [80 90]]
b2[1][0:2] :  [40 50]
modified b2
[[10 25 35]
 [40 55 65]
 [70 80 90]]
